defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "text"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

title: Usecue web development
description: Website development and hosting
url: https://www.usecue.com
twitter: jhvanderschee