defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "portfolio" # previously `post` in Jekyll 2.2.
    values:
      layout: "portfolio"

title: Usecue web development
description: Website development and hosting
url: https://www.usecue.com
twitter: jhvanderschee
permalink: /blog/:year/:month/:day/:title/

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/