defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      language: en
  -
    scope:
      path: "nl" # an empty string here means all files in the project
    values:
      layout: "page"
      language: nl
  -
    scope:
      path: "_posts/en" # an empty string here means all files in the project
    values:
      layout: "post"
      language: en
      permalink: blog/:title/
  -
    scope:
      path: "_posts/nl" # an empty string here means all files in the project
    values:
      layout: "post"
      language: nl
      permalink: nl/blog/:title/
  -
    scope:
      path: "_portfolio/en" # an empty string here means all files in the project
    values:
      layout: "portfolio"
      language: en
      permalink: portfolio/:title/
      _comments: 
        image: desktop 1236 x 782
        mobile_image: mobile 419 x 703,5
  -
    scope:
      path: "_portfolio/nl" # an empty string here means all files in the project
    values:
      layout: "portfolio"
      language: nl
      permalink: nl/portfolio/:title/
      _comments: 
        image: desktop 1236 x 782
        mobile_image: mobile 419 x 703,5

title: Usecue web development
description: Website development and web hosting
url: https://www.usecue.com
twitter: jhvanderschee

collections:
  portfolio:
    output: true    